name: Deploy to EC2 for testing

on:
  push:
    tags:
      - 'latest'  # This triggers the workflow on pushing the latest tag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: SSH into EC2 and Deploy
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Pull the latest Docker image
          docker pull omkokate2902/family-tree-testing:latest

          # Stop and remove the existing container if it exists
          if [ "$(docker ps -q -f name=family-tree-testing)" ]; then
              docker stop family-tree-testing
              docker rm family-tree-testing
          fi

          # Run the new container
          docker run -d -p 3000:3000 --name family-tree-testing omkokate2902/family-tree-testing:latest